### ISSUE TITLE
Code review of python export scripts

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1077]
`py_func/__init.py__`
* Just add a comment to tell us noobs why it’s there

`QuinCetoCarbonPortal.py`
* `25-27` Just put in the filenames here. Remove any clues to your local filesystem structure...
* `39` **NEVER PUT PASSWORDS IN CODE FILES. THESE ARE PUBLIC.**
* `60` As a central script you’ve got the right idea - it’s pretty minimal and just calls other functions to do things. I’d just take it a step further, so each module is completely responsible for everything it does and there’s no processing done here at all. So this line just becomes “If OTC then call OTC function”. If any of those sub-modules end up doing the same thing, those shared functions can be pulled out into their own modules (as you’ve already been doing in meta_handling)

`quince_comm.py`
* `32` We can put these lines in as debug logs. Then we can configure the logger to decide whether we want to see them or not (I assume you know how this works - if not ask me)
* Why doesn’t get_export_list use the talk_to_quince function? It doesn’t take a dataset id, but you could pass in `-1` (or make it an optional parameter to the function) and then talk_to_quince will not send it.
* `talk_to_quince` is a bit of a buffy-speak function name. You can have some fun in comments being slightly flippant (it helps to let off steam and puts some humanity in the code) but function names etc should be more formal (`make_quince_call` or something like that). It’s likely that I’m guilty of this at times, so feel free to call me a hypocrite if you ever see it...

`meta_handling.py`
* `76/79` These are Magic Strings - they should be made into constants at the top of the module. I see you’ve already done this for `cmems_converter.py`, so you’re probably just learning as you go along :)
* There’s a mixture of variable naming styles: `acquisitionInterval`, `additional_information`. Be consistent throughout according to the language’s code style. I believe `additional_information` is correct for Python. Check all code...
* `74, 97/98` `acquisitionInterval` seems to build an array and then only ever use it to pull the values back out. Simpler to read if you make separate variables. On which note….
* If you’re making a variable and then only using it once, don’t bother making the variable - unless it makes the code hard to read (e.g. makes lines excessively long). For most of these I don’t think it will. In any case, lines `84` and `85` are certainly redundant.
* `171` I don’t think it’s necessary to split these up. `root.find(‘startdate’).text = startdate` is OK. But then again...
    * What if `root.find(‘startdate’)` doesn’t find anything? Leaving the code split like you have it is good, and you can check that the element actually exists.
    * I know that `startdate` is actually a few levels down in the XML tree. Are we trusting that the file is correct and therefore if we find a `startdate` *anywhere* then we’re happy? What happens if there’s more than one?  This is largely a philosophical question - it may be that we are happy for it to be this way. Just something that needs to be thought about. Or maybe you have and you’ve decided that it’s fine as it is. There’s a balance between excessive checks and not enough, and the choice isn’t always clear cut. So I’d like to know how you’ve thought about it.

`cmems_converter.py`
* There are some magic strings at the top, and elsewhere in the code you haven’t bothered with them. So when do you use them and when not? Again, there’s no correct answer. But let’s talk it through and see where we end up.
* Since a lot of this is my code, do your own review of it. Anything in my approach that you disagree with, or want to ask about?

`copernicus.py`
* In `upload_to_copernicus`, you never close the FTP connection. Although it will be closed when the script quits, best to be tidy and do it explicitly (preferably in a `finally` block). It’s much safer to do this, especially with files. The library or even the OS might be doing all sorts of clever things that you’re not aware of (e.g. caching), and if you don’t explicitly close connections and files it may leave things in a broken state. This is particularly dangerous for files on disk - I've often ended up with the last piece of data not actually being written to the file...
* `38` You use `if upload_result is 0:`, while I use `if upload_result == 0:`. Which is more Pythonic? Find out, and let’s be consistent between us.

**Comment by MarenKK** [comment]
Ref issue #1025
