### ISSUE TITLE
Issue try wrong login

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#1085]
If you try to log in with an account that does not exists, the following ugly error is displayed to the user: 

![wrong_login](https://user-images.githubusercontent.com/5442807/51535668-74a61c80-1e49-11e9-9b2b-f679983a1bb4.png)

**Comment by squaregoldfish** [comment]
Fix #1086 first, so we get rid of the ugliness too.
