### ISSUE TITLE
Speed up data processing

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#1100]
Love the speed updates to the data reduction. However, what now slows down processing, is the jobmanager sleeping: 

![speed_up_data_reduction](https://user-images.githubusercontent.com/5442807/53084766-c6ea6400-3501-11e9-8172-d9f3b87b3bd1.png)

As you can see, the jobmanager sleeps for 8 seconds during the first round, and 13 sec on the next. Polling the database for new jobs should be a very quick query. Could we just change the sleep interval from however much it is now, to perhaps 1 sec or something?

**Comment by squaregoldfish** [comment]
We can probably bypass the sleep interval when a new job is added, something like:

When job is added, if there's a free thread then start it immediately.
