### ISSUE TITLE
Data sets given wrong prefix

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1412]
If you change instruments in the data set list, and then create a new dataset, the automatically generated dataset name has the platform code for the original instrument.

**Comment by squaregoldfish** [comment]
To reproduce:

Select an instrument
Open the Create Dataset page, and generate a dataset ID. DO NOT CREATE THE DATASET
Cancel
Change instrument
Open the Create Dataset page, and generate a dataset ID. Has platform ID of previous instrument.

**Comment by MarenKK** [comment]
dataset ID is first displayed(created?)  when start date is set in new dataset

**Comment by squaregoldfish** [comment]
Your assessment is correct. I must learn to write these things without the assuming that I’ll be the one reading them and know how it works…

**Comment by MarenKK** [comment]
getCurrentInstrument not triggered when button 'create New Data Set' is clicked.
