### ISSUE TITLE
Update Copernicus netCDF format

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1440]
There's a new version of the CMEMS netCDF format. We must update the `cmems_converter` to conform to it.

Also add a note about ICOS as the source of the data in the metadata somewhere.

**Comment by squaregoldfish** [comment]
scale factors and offsets are implemented. Remaining jobs:

- Time dimension is no longer UNLIMITED
- Check everything against the specification doc (https://drive.google.com/file/d/1D0h9hSoIhGC7QiOZ-9m_4BIVLZqRD1Zr/view)
- Run agains the format checker (need to ask for it)

**Comment by MarenKK** [comment]
Finished and ready for release
