### ISSUE TITLE
NRT latest should be latest 30 days of observations, not last 30 calendar days of data.

### ISSUE THREAD

**Issue by MarenKK** [BjerknesClimateDataCentre/QuinCe#1548]
For march release update

**Comment by squaregoldfish** [comment]
Is that up to 30 days before the last observation, or the last 30 days that have observations (in which case the span of files in the folder may be longer than 30 days)?

**Comment by MarenKK** [comment]
last 30 days that have obeservations. The latest file should always contain 30 files. The temporal period is not of concern.
