### ISSUE TITLE
Atmospheric xCO₂

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1762]
Atmospheric xCO₂ is required as a published column alongside pCO₂ and fCO₂. This is calculated during data reduction, but should be included as a standard part of final output.

~~The exporter has an option to show intermediate calculated values or just the final values - adjust that so we can specify that individual calculated values should always be exported. Maybe it does that already, or not.~~

**Comment by squaregoldfish** [comment]
Once we've done this and registered the column with the carbon portal, we can simply re-export all datasets as new versions and it'll all work. Probably.

**Comment by MarenKK** [comment]
#1743
