### ISSUE TITLE
QC-page not loading on first try

### ISSUE THREAD

**Issue by MarenKK** [BjerknesClimateDataCentre/QuinCe#1855]
![Screenshot from 2020-09-11 09-45-33](https://user-images.githubusercontent.com/43780941/92886408-e7477f80-f413-11ea-95b4-8ebf1b6f0d2d.png)

**Comment by MarenKK** [comment]
Works on first try when explicitly choosing instrument

**Comment by squaregoldfish** [comment]
This happens with Mario every time
