### ISSUE TITLE
Huge negative xCO2 data points not detected by QuinCe range check

### ISSUE THREAD

**Issue by cla023** [BjerknesClimateDataCentre/QuinCe#2100]
The Finnmaid Los Gatos labelling dataset (34FM20200815) contained about 1500 data points between the range -734199.463 to -6387.644. These were all flagged by QuinCe as good (2). Why were these not detected by the range checker?

<img width="491" alt="out_of_range_not_detected" src="https://user-images.githubusercontent.com/33487925/117285430-4dcc5280-ae68-11eb-9559-bf5fe1ae967f.png">

**Comment by squaregoldfish** [comment]
The original xCO2 value is fine, so something's gone haywire in during the calibration.

#732 would detect this.

**Comment by squaregoldfish** [comment]
The original cause of this was a misreading of missing values (999999), which were processed as valid values. Since this has been fixed in #1873 I'm closing this issue. The referenced issues above will get sorted out in their own time.
