### ISSUE TITLE
Tab separated input file with comma in header gets wrong header in export file

### ISSUE THREAD

**Issue by cla023** [BjerknesClimateDataCentre/QuinCe#2268]
In 'QuinCe Labelling' there is a station 'Oeastergarnsholm (Labelling)' with one dataset: 77FS20201021. This dataset has a tab separated input seabird file which contains comma in the headers, e.g. 'Oxygen, SBE 43 [mg/l]'. In the export file this header is separated into two headers. The data columns is still correct though. See attached the input file and the exported file (export as ICOS Labelling).
[OES_Seabird_2021.txt](https://github.com/BjerknesClimateDataCentre/QuinCe/files/7351888/OES_Seabird_2021.txt)
[77FS20201021-ICOS OTC Labelling.csv](https://github.com/BjerknesClimateDataCentre/QuinCe/files/7351889/77FS20201021-ICOS.OTC.Labelling.csv)

**Comment by squaregoldfish** [comment]
Need to escape commas in headers, or just suppress them.
