### ISSUE TITLE
Duplicate parameter columns in QuinCe labelling export file

### ISSUE THREAD

**Issue by cla023** [BjerknesClimateDataCentre/QuinCe#2275]
The exported file from dataset 77FS20201021 (instrument 'Östergarnsholm labelling') contains the column 'temperature' twice (the accompanying flag and comment columns also appear twice). Please see attached file below. 

Is this a bug or has the instrument been created in a wrong way? I believe I drag and dropped the SAMI temperature ('temperature') to the SST and Teq spot, and drag and dropped the seabird temperature ('T') to the diagnostic temp (or diagnostic misc.) spot - or that is what I tried to do at least.

[77FS20201021-ICOS OTC Labelling.csv](https://github.com/BjerknesClimateDataCentre/QuinCe/files/7375563/77FS20201021-ICOS.OTC.Labelling.csv)

**Comment by squaregoldfish** [comment]
Somehow two sensors have been given the same name (in the same file definition). Work out why and stop it from happening.

**Comment by squaregoldfish** [comment]
Proper fix in place now. Instruments already defined with duplicate sensor names will have to stay.
