### ISSUE TITLE
Flags from the raw temperature column not past on to the 'Temp [degC]' column

### ISSUE THREAD

**Issue by cla023** [BjerknesClimateDataCentre/QuinCe#2276]
The exported file from dataset 77FS20201021 (instrument 'Östergarnsholm labelling') contains temperature column ('temperature') which is sometimes flagged as 4 (Constant for too long). These flag 4 are not carried on to the 'Temp [degC]' column which is the same data (both temp from the SAMI sensor) but I guess this column represents the temperature assigned as SST in Quince. Should these flags really be missing from the 'Temp [degC]' column?

**Comment by cla023** [comment]
[77FS20201021-ICOS OTC Labelling.csv](https://github.com/BjerknesClimateDataCentre/QuinCe/files/7375580/77FS20201021-ICOS.OTC.Labelling.csv)

**Comment by squaregoldfish** [comment]
This is related to the new data interpolation functions, that recognises Bad flags and tries to interpolate values from Good data. So although the data at the specified point is Bad (temperature), the value used in the final calculation (Temp) is actually good.

This example does illustrate a bug in that the interpolated values aren't being marked properly, so I'll fix that.
