### ISSUE TITLE
Correcting SST/Eq

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#268]
Denis co-locates SST and EqT by offsetting the EqT. Offset the EqT  to equalize the difference between the intake-temperature and the equilibrator temperature.

In this version the offset should simply be decleared in the instrument definition as a positive number of seconds. All parameters in the dataset, except the intake temperature, should be shifted.

(If there are more parameters that are measured at the intake, these should also not be shifted, but this is not handled here.)

~~The way to do this automatically is to lag the SST to get the maximum correlation between the SST/EqT across the whole data set.~~

~~Presumably this means offsetting all the other measurements (CO<sub>2</sub> etc.) in line with the EqT adjustment.~~

**Comment by squaregoldfish** [comment]
Do we have to account for an offset between the equilibrator and the CO2 sensor? Is this even possible, given the data we have available? I have a suspicion that it isn't. Also, the equilibrator and the CO2 sensor should be at roughly the same temperature, so there probably isn't a significant change anyway. Check with Denis though.

**Comment by squaregoldfish** [comment]
Once the correct offset has been calculated, the equilibrator temperature, pressure and CO2 measurements should be moved to match the SST record.

We need to record somewhere in the dataset what offset was applied, so it can be recorded in the metadata when the data set is published. In the long run there are a number of things like this we need to record (what decisions QuinCe made while processing the data), so we'll need a mechanism to handle it.

**Comment by squaregoldfish** [comment]
Having discussed this with Denis, this probably shouldn't be automated, because it's too prone to error. We can either have a fixed offset defined as part of the instrument, or make a UI for the user to adjust the offset for the data set when it's defined (after data extraction but before calculation).

The first option is simplest, but assumes that the offset won't change over time. And since it's sensitive to flow rate, I'm not sure that's a valid assumption.

**Comment by jonasfh** [comment]
There are some approaches to make this practical: 

1. Split the dataset-data table into two tables: one handling the position (incl. time) and one handling the parameter data. This table will be huge (we've discussed this)
2. Split dataset-data into three tables: One handling the position (incl. time), one containing parameters at the intake, one with parameters at the equilibrator.

Both these approaches allow for attaching data to a different time and location information than what is in the collected data. Approach one is the most generic and flexible, but also the least efficient. Using the second approach, the db-routine rewriting will be minimal.

**Comment by squaregoldfish** [comment]
Denis's approach is to use interpolation - so we would take the SST value, and interpolate the measurements on the equilibrator side of things to get a value at the correct offset from the SST measurement time.

This is relatively difficult to implement with the current setup, and also the current practice of applying a QC flag to a whole record is problematic in terms of selecting which record is actually flagged. Therefore this will wait until individual sensor QC is in place (#576). This will allow individual sensor measurements to be flagged bad, and the interpolation can operate on the remaining values. 

There should be limits on the time over which interpolations can be performed before the values become invalid. In those cases there are a few options - use the closest available measurement, extrapolate the trend from the last few measurements (problematic with sensor noise and coastal high variability), or simply not calculate a value at all.

**Comment by squaregoldfish** [comment]
Possible graphical interface for defining the offsets
![ink-image](https://user-images.githubusercontent.com/733650/61588230-06dc7280-ab98-11e9-9f6f-ecc86ac91dfb.png)

Note that the time offsets (in purple) can show both the interval to previous sensor and total from water intake.

**Comment by squaregoldfish** [comment]
**Notes from call with Denis**

Offsets cannot be fixed on an instrument, so the above idea is toast. Instead, when a dataset is defined we have to specify the offset. Only SST/EqT is important here, and we move all other values to the SST value.

I can have an automatic algorithm that tries to find the best offset. This can simply offset the two variables at several lags (up to 10 min) and work out which has the highest correlation - we choose that one. The user can then tweak it if they wish. Possible interface below:
![ink-image](https://user-images.githubusercontent.com/733650/65977236-da838300-e471-11e9-86df-0a340f481cf4.png)
As the user tweaks the offset, the plots update.

Denis wondered if there's a one-shot way to do this? Plotting EqT vs SST and running a least squares fit would give an optimal slope with r², but how is that translated into an offset?

**Comment by squaregoldfish** [comment]
This needs to happen between the Data Extraction Job and the Locate Measurements Job. We need a way to interrupt the job flow and have a User Action stage which will bring up the interface. Once it's set, resume the job flow. Before AutoQC job is probably best, because then it won't interfere with recalculation during manual QC.

This can probably be defined at the InstrumentVariable level, and needs the DataSet status to have more options.

The chosen offset must be set as an attribute of the dataset. The Data Reduction Job must take this into account when finding values for measurements. (Base measurements off SST instead of CO2 in Locate Measurements? Or in Data Reduction work out the SST and edit the time of the measurement to match it?)

**Comment by squaregoldfish** [comment]
Cross correlation is the thing we need.

Need to work out how to handle SST and EqT in different files and on different timing schemes. Maybe there's a library out there that can handle it.

**Comment by squaregoldfish** [comment]
Do the offset as part of the `LocateMeasurementsJob`. Then the user can edit at the end, which will trigger recalculation from that job. (NRT will not have the option)

The offset will be stored in the dataset somehow. If it's null, the job will calculate it. Otherwise it will apply what's there.

**Comment by squaregoldfish** [comment]
This can potentially be applied to any pair of sensors, and some will be negatively correlated. So the cross-correlation should find the closest to either 1 or -1.

**Comment by squaregoldfish** [comment]
It may be that the offsets aren't fixed for the full length of a dataset. Do some experiments with SOCAT and ask Harald.

**Comment by squaregoldfish** [comment]
Implementation plan:

- Create groups of sensors in the instrument definition. Define the linking sensors
- Algorithm for detecting peaks/troughs and lining them up through the course of a dataset
- UI for reviewing and editing match points

Offsets stored as part of the dataset properties

**Comment by squaregoldfish** [comment]
Feeback from Tobias:

- Add the ability to view another plot (eg water flow) to find points where it's likely an offset change will occur
- Add a plot the shows the delta between the two variables to see where the relationships change suddenly (toggle applied offset option?). This can be alternated with the current offset time series in the bottom left
- Toggle axis locks, so we can switch between having the two variables on separate axes on the same axis. Tobias got confused by SST looking higher than EqT.
- Add correlation stats (applied and non-applied) to show whether it's getting better or not.

**Comment by squaregoldfish** [comment]
It's possible that there might be a group between entries of interest, i.e.

SST <-> SSS <-> EqT

Can we make this work? I can't immediately see how.

**Comment by squaregoldfish** [comment]
We seem to have something that works. Check with interested parties (Tobias/KPH/Denis)

**Comment by squaregoldfish** [comment]
Handle Type columns. If we offset directly onto a measured value, it should be marked M.

This may mean that we need to store the Type in the MeasurementValues JSON.
