### ISSUE TITLE
Handle empty line at end of input file

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#364]
As per title

**Comment by jonasfh** [comment]
I Cannot reproduce this. When does the error occur? Needs description

**Comment by squaregoldfish** [comment]
@jonasfh Either way, your fix for empty lines in files being pushed today should mean that any file with empty line(s) at the end will not cause issues, correct? In which case this can just be closed.

**Comment by jonasfh** [comment]
Handled in issue #531
