### ISSUE TITLE
Empty file data in new instrument

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#468]
New instrument: uploading a new file sometimes gives empty data in the preview. Could be a parsing issue - check for exceptions.

(G O Sars CO2 data)

**Comment by squaregoldfish** [comment]
Seems to be related to short files.

**Comment by jonasfh** [comment]
Please add a file example to this issue

**Comment by jonasfh** [comment]
Error happening if instrument file shorter than MAX_DISPLAY_LINES (250 lines)
