### ISSUE TITLE
Assigning combined date and time gives error

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#475]
If the Combined date and time is assigned, the summary on the left shows "error".
![screen shot 2017-07-31 at 15 02 50](https://user-images.githubusercontent.com/733650/28778860-58c20cd2-7601-11e7-82bc-a79a21d0594b.png)

**Comment by jonasfh** [comment]
Cannot reproduce this issue. Testing on SimonStevin file 170411.csv

![combined_data_time](https://user-images.githubusercontent.com/5442807/37587779-84a6dbce-2b60-11e8-8977-d1a262331145.png)

**Comment by squaregoldfish** [comment]
Hmm. Could be that a specific file format is/was broken. Since the field in general works, closing this out. If it comes up again we'll make a new issue.
