### ISSUE TITLE
Run Type is stored with a column name

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#485]
The Run Type is stored in the database with whatever column name was last entered in the app. It doesn't really matter because it's never shown, but it should be fixed to 'Run Type'

**Comment by jonasfh** [comment]
I dont see where this data goes? Is it in the dataset_data - table, or in the file_column - table? Data in the file-column - table seems to be handled in saveInstrument() in NewInstrumentBean, and it already always says "Run Type" as both sensor_type and sensor_name. Data in dataset_data, however, has a run_type - column that says EQU in my current dataset.

Please clarify which column in which table should always be "Run Type" ...
