### ISSUE TITLE
Log Out should be a page

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#491]
Currently, clicking the Log Out tab instantly logs you out. It should put up a confirmation dialog.

**Comment by squaregoldfish** [comment]
Popup dialog

**Comment by jonasfh** [comment]
I don't think wee need this functionality. If you click Log out you probably just want to log out. If you didn't, you can just log back in.

**Comment by squaregoldfish** [comment]
Fair enough. Chances are, no-one will even use the link anyway...
