### ISSUE TITLE
Rationalise reference assignments into single table

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#496]
The reference assignments (gas standards and calibration coefficients and eventually externals calibrations #495) are currently stored in separate tables. This means we can't write safe generic code to interrogate these, because the table name always needs to be specified which is a security issue.

Reference assignments should all be stored in a single table, with a structure something like:
* instrument id
* reference type (gas standard, coefficients)
* reference name (name of standard/sensor)
* reference date
* values (a comma-separated list of Doubles) (or a JSON array)

**Comment by squaregoldfish** [comment]
I believe the abstract `ExistingReferenceAssignmentValidator` can be restricted to always restrict the search to a given instrument, and get rid of the `restrictionField` parameters.

**Comment by squaregoldfish** [comment]
Pay particular attention to the `DATETIME` requirement in #495 .

**Comment by jonasfh** [comment]
Ref #597

**Comment by squaregoldfish** [comment]
This has been done as part of other changes.
