### ISSUE TITLE
Auto-start next job

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#504]
When one job, finishes, instantly check for any other waiting job and start it. ATM it just falls back on the scheduler, which causes a few seconds' unnecessary delay.

**Comment by MarenKK** [comment]
#234

**Comment by squaregoldfish** [comment]
Setting the job scheduler interval to one second basically has the same effect, and doesn't seem to impact things otherwise. Plus it's a lot simpler than trying to build overrides into the job scheduler.
