### ISSUE TITLE
Data averaging

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#523]
Add an averaging option to instruments. All raw values are averaged over _n_ seconds as they are extracted from the raw data. Calculations are performed on the averaged values.

**Comment by jonasfh** [comment]
Ref #558

**Comment by squaregoldfish** [comment]
This could be configured to only average measurements, and not calibration runs. See also #1283

**Comment by squaregoldfish** [comment]
We should process all files at native resolution, and perform averaging at export time as required.
