### ISSUE TITLE
Convert all Date to LocalDateTime

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#526]
It's possible everywhere, with conversion to Dates for database calls at the last second. (Make a utility method for the conversions)

**Comment by squaregoldfish** [comment]
Include Calendar objects too

**Comment by squaregoldfish** [comment]
Conversion methods added to `DatabaseUtils`.

**Comment by MarenKK** [comment]
JODA time
