### ISSUE TITLE
Allow user to set limits on diagnostic sensors

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#546]
No QC is currently performed on diagnostic sensors (i.e. `usedInCalculation == false`), because we can't tell what the thresholds for an individual instrument are.

Allow the user to enter these when the sensors are defined. These should also be editable if possible.

The sensor assignment should have a Properties object for storing these limits.

**Comment by squaregoldfish** [comment]
This could (should) be done for all sensors, in fact. The ones for main sensors will override the defaults. See also #289

**Comment by jonasfh** [comment]
Ref #606

**Comment by squaregoldfish** [comment]
Ref #576

**Comment by squaregoldfish** [comment]
Wa can start with a customisable range check for all sensors and work from there.

**Comment by MarenKK** [comment]
#289

**Comment by squaregoldfish** [comment]
Closed by #2624
