### ISSUE TITLE
Ensure that records have date and position during extraction

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#575]
If they don't the records should be flagged as FATAL (in the calculation record).

I'm not sure how we deal with these in terms of QC yet. We could report them, but never show them in the QC screen, but the user should be able to see them somehow.

**Comment by squaregoldfish** [comment]
See also #589

**Comment by jonasfh** [comment]
Ref #655

**Comment by squaregoldfish** [comment]
Positional part will be done as part of #1451
