### ISSUE TITLE
Apply sensor calibration

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#579]
When extracting data from a file, perform the necessary sensor calibration on it.

Look in `calibration` table for matching `instrument_id` and `target = sensorName`, and `type = SENSOR_CALIBRATION`. Instantiate the class and apply the formula.

The calibration should probably be applied somewhere around line 824 in DataSetRawData.java in package uk.ac.exeter.QuinCe.data.Dataset

**Comment by squaregoldfish** [comment]
Benguela Stream is set up and waiting for this.

**Comment by squaregoldfish** [comment]
![picture](https://user-images.githubusercontent.com/733650/33084413-360335c4-cee2-11e7-89c2-8482e098cf91.jpg)

**Comment by jonasfh** [comment]
Define sensor using the following columns and calibration values for temperature and pressure: 

Parameter = Run Type
Date/Time = As labelled
Latitude = Latitude + NorS
Longitude = Longitude + EorW
SWTemp = Intake Temperature
Equilibrator Temp = PT100_1 [mV]
Equilibrator Pressure = Pres2 [mV]
CO2 = LCO2B [umol/mol]
xH2O = LH2OB [mmol/mol]
Salinity = SBSal



Equil Temp equation = 9.96x + 0.7235
Equil Pres equation = 40.419x + 878.1
