### ISSUE TITLE
Remove Run Types configuration

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#586]
The Run Types configuration should no longer be required.

Each Core variable (ocean fCO2, atm pCO2, pH etc.) will be defined as a separate entity. Therefore, the run types for each Core variable will be INTERNAL_CALIBRATION (for gas standards) and MEASUREMENT. There shouldn't be any need for anything else.

This should be done as part of #1121. Each measurement will be given a `measurement_type` according to the above. In the long run we can add EXTERNAL_CALIBRATION for bottle samples etc.

**Comment by jonasfh** [comment]
Ref #603
