### ISSUE TITLE
New 'averaging' method - last of run

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#588]
Some instruments run for a while to equilibrate, and then the last record of each run is used for the CO2 value.

We still need to be able to review the measurements running up to that point, to make sure it's equilibrating properly.

**Comment by squaregoldfish** [comment]
Another option is the ability to average over the last n measurements, or the last n minutes of each run

**Comment by squaregoldfish** [comment]
Regarding the last point: Do we average the sensors then do the calculation, or do the calculation and average the fCO2 values? I guess the former so we can include the SST/Sal etc in SOCAT correctly, but double-check with PIs. (Or SOCAT, so see what we *should* be doing).

**Comment by MarenKK** [comment]
#408

**Comment by squaregoldfish** [comment]
This has been covered by CONTINUOUS/PERIODIC measurement modes.
