### ISSUE TITLE
Create cusomtisable config

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#602]
Config paths are currently coded in web.xml, which causes problems for the multiple developer scenario. Find a good approach.

**Comment by jonasfh** [comment]
In issue #702, config files are handled with some scripts to search - replace text. However, we need to let git help us with this by setting up a filter: 

- git.config file specifying clean and smudge filters
- git.attributes specifying what method to run on clean / smudge

**Comment by jonasfh** [comment]
The smuge-clean approach don't really work for us. We should close this and revisit it if the need reappears (perhaps when a new programmer appears?)
