### ISSUE TITLE
Load diagnostic values into Calculation Records

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#614]
The diagnostic values aren't explicitly defined in the ColumnConfig for the QC routines, so it's hard to work out what to do with column indices and making them visible to the QC routines when they run.

Left out for now, but they need to be in.

**Comment by jonasfh** [comment]
Ref #576

**Comment by squaregoldfish** [comment]
Diagnostic data is extracted, and can be viewed in plots. Maps are currently broken.

**Comment by squaregoldfish** [comment]
Now only need to add values to the table.

**Comment by squaregoldfish** [comment]
Diagnostic values are added, but cannot be QCed. This will have to wait until later.
