### ISSUE TITLE
Hour of day date-preview using DD instead of dd

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#627]
The Hour of day preview fails if the day of year to preview is > 99. The offending line is in 
NewInstrumentBean.java around line 85: 

`private static final DateTimeFormatter PREVIEW_DATE_TIME_FORMATTER = 
DateTimeFormatter.ofPattern("yyyy-MM-DD HH:mm:ss");`

should be

`private static final DateTimeFormatter PREVIEW_DATE_TIME_FORMATTER = 
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");`

**Comment by squaregoldfish** [comment]
Might as well fix it, since it's a one-line job :)
