### ISSUE TITLE
Error clicking View Deployments 

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#629]
At the Instruments - tab your instruments are listed. For each instruments there is a View deployments - button. However, when you click View deployments you'll get an error, like: 

> Internal Error
> Something horrible has happened. Please accept my apologies. Details of the horrible thing are below. If the horrible thing keeps happening, please copy the details into an email and send it to quince@uib.no.
> uk.ac.exeter.QuinCe.utils.RecordNotFoundException: No external standard names found for instrument 21 at uk.ac.exeter.QuinCe.data.Instrument.Calibration.ExternalStandardDB.getTargets(ExternalStandardDB.java:77) at uk.ac.exeter.QuinCe.data.Instrument.Calibration.CalibrationDB.getTargets(CalibrationDB.java:155) at uk.ac.exeter.QuinCe.data.Instrument.Calibration.CalibrationDB.getCurrentCalibrations(CalibrationDB.java:104) at uk.ac.exeter.QuinCe.web.Instrument.CalibrationBean.loadCurrentCalibrations(CalibrationBean.java:177) at uk.ac.exeter.QuinCe.web.Instrument.CalibrationBean.start(CalibrationBean.java:68) at 
...

**Comment by jonasfh** [comment]
ref #669

**Comment by squaregoldfish** [comment]
This was caused by an instrument ID left in the user preferences after that instrument was deleted from the database.

This was fixed as part of #669
