### ISSUE TITLE
Only the most recent external standards are used

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#767]
The Data Reduction Job uses only the most recently deployed standards, regardless of the date of the data set being processed (`CalibrationDB.getCurrentCalibrations`).

A method to get the calibrations based on a date is being developed for issue #579, and should be applied here too.

**Comment by jonasfh** [comment]
This issue seems to be resolved. The current handling is like this: when reducing a data set, the available external standards with the most recent date **earlier than the start date of the data set** is used.
