### ISSUE TITLE
extractDoubleFieldValue fails with comma as thousands-separator

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#780]
Some files have data with float-data looking like this: 1,012.7 meaning 1012.7

The offending line is in class DataFile around line 490 

```
result = Double.parseDouble(field);
```

The issue is probably solved most easily by simply stripping commas from the strings to parse

To test try to add a file column with a comma, like the schuster - data files from the Benguela stream, the Pres - column has this format.

**Comment by squaregoldfish** [comment]
#264
