### ISSUE TITLE
Add diagnostic sensor configuration to test setup

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#926]
The diagnostic sensors configuration was not setup for the test environment. This comes down to adding the following line at the end of `WebApp/junit/resources/configuration/quince.properties`

    diagnostic_sensors=Temperature,Pressure,Air Flow,Water Flow,Voltage

**Comment by squaregoldfish** [comment]
No longer relevant due to database changes.
