### ISSUE TITLE
Use DatabaseUtils method to build SQL with IN clauses

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#952]
There's a method `DatabaseUtils.makeInStatementSql` that can build a `PreparedStatement` with the correct number of parameters for a given list. We should use this for all queries with `IN` clauses to reduce the chance of SQL injection attacks. (Also make a `NOT IN` equivalent).

Items to check:

- [x] CalculationDB.java 364
- [x] CalculationDB.java 408
- [x] CalculationDB.java 493
- [x] CalculationDB.java 556
- [x] CalculationDB.java 940
- [x] CalculationDB.java 364
- [x] CalibrationDB.java 97
- [x] CalibrationDB.java 372
- [x] DiagnosticDataDB.java 45
- [x] DiagnosticDataDB.java 222
- [x] DiagnosticDataDB.java 225
- [x] JobManager.java 43

**Comment by MarenKK** [comment]
#459
